name: Render ping every 15 minutes

on:
  schedule:
    # Runs every 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  curl-website:
    runs-on: ubuntu-latest
    
    steps:
      - name: Ping Render service
        run: curl -I https://perla-metro-stations-service.onrender.com
